### ISSUE TITLE
[feature] any way to remove/re-add an existing server?

### ISSUE THREAD

**Issue by flowy0** [allen-li1231/zeppelin-vscode#11]
Hi, 

Is there any way to remove an existing server and re-add it? (edit a user json file or anything)?
I had actually reset/updated my server and I get a Status 302 error at the side when I try to connect.

**Comment by allen-li1231** [comment]
You may change your Zeppelin credential or server url via VSCode command palette (ctrl+shift+p to open) and type `>zeppelin` to find all extension commands.

In you specific case, I assume that you have restarted the server with credential or server url unchanged. You can simply reload the window (by entering `>reload window` in command palette) or restart VSCode to trigger re-login.

**Comment by flowy0** [comment]
Sorry for the late reply. I have tried `Set Zeppelin Credential`.
I have the following error when i try to re-login. 

<img width="388" alt="image" src="https://github.com/allen-li1231/zeppelin-vscode/assets/9532712/b7c44cad-a61f-47ce-81d7-7634595a46db">

**Comment by allen-li1231** [comment]
This is probably a bug, would you take time to try out the pre-release version?

**Comment by flowy0** [comment]
How can I try the pre-release version?

**Comment by flowy0** [comment]
> @flowy0 This is probably a bug, would you take time to try out the pre-release version (0.2.8)? Please let me know if login succeeds on your side. Appreciated!

Managed to test the pre-release and re-connect to my server. Thanks!
