### ISSUE TITLE
"AxiosError: Request failed with status code 404" when trying to run cell.

### ISSUE THREAD

**Issue by ant0nk** [allen-li1231/zeppelin-vscode#14]
Opened notebook, conneted to server but when I try to run any cell I see "AxiosError: Request failed with status code 404" message.

**Comment by allen-li1231** [comment]
Hi,@ant0nk .
I assume you have logged in without an error. A 404 error in execution  output means one of the following:
* The paragraph of the cell could not be found in the notebook. Would you check if the same cell's status bar shows a ⚠️ when you type some code in it?
* The notebook doesn't exist on the server side. In this case, the extension would have prompted you to specify the path to save the notebook when you open it. You may close the notebook and reopen it to trigger the prompt again if you have missed it.
