### ISSUE TITLE
When opening notebook (.zpln file) in VS Code it is read only

### ISSUE THREAD

**Issue by smitty-codes** [allen-li1231/zeppelin-vscode#2]
@allen-li1231 Thanks for making this extension. I have followed the instructions you have in the VS Code extensions page but when I export an existing notebook out to a .zpln file and then open it within VSCode, it keeps marking it as read-only. Is this expected or maybe my setup is not configured correctly? I seem to have gotten it connected to my spark cluster also and everything works in regular Zeppelin web app just not the extension.

What I'm really after is VSCode's intellisense capabilities so I thought I'd install your extension, pull in the notebook file and then take advantage of Metals Scala extension to get intellisense/autocomplete on the scala code in the notebook. This is because the intellisense in vanilla Zeppelin web app leaves alot to be desired. Maybe this idea won't work?

My setup is as follows:
- MacOS
- VSCode v1.84.0
- Spark v3.2.1 (running in a cluster across machines in my local network)
- Zeppelin web app (port 9090) and spark master (default spark ports) are all running on my local machine

thanks

<img width="1017" alt="image" src="https://github.com/allen-li1231/zeppelin-vscode/assets/3335939/81e3b6f3-39a3-4a88-aeb8-3133b2568061">

**Comment by allen-li1231** [comment]
@smitty-codes Let me know if you have any further problems, or this issue will be closed in 5 days.

**Comment by allen-li1231** [comment]
Hi @smitty-codes , in the new version (0.2.1) the logic of locking zpln file has been removed, as I believe lots of people are also perplexing if it is expected. Let me know if you have encountered any further problem, thanks.
