### ISSUE TITLE
[feature] progress bar when running cell?

### ISSUE THREAD

**Issue by barius** [allen-li1231/zeppelin-vscode#4]
Any plans on adding progress indicator of an running cell? :)

**Comment by allen-li1231** [comment]
Unfortunately VSCode has not yet provided any cell-level progress bar controll API, so it would be difficult to implement a progress bar that is identical to Zeppelin.
It is much easies to make a notification window to show a progress of one selected running cell. I can do that as a remedy. Meanwhile I will keep checking if cell-level one is viable.

**Comment by barius** [comment]
In vscode's Jupyter notebook you can
```
pip install IProgress ipywidgets
```
then
```
from tqdm.notebook import tqdm
```
and you get a progress bar
<img width="753" alt="图片" src="https://github.com/allen-li1231/zeppelin-vscode/assets/2980072/74e78e9e-36cb-4841-ac8f-84ee12a26e01">

no idea how that works :P

**Comment by allen-li1231** [comment]
Thank you for the information, I will look into that. Will notify you the progress.

**Comment by allen-li1231** [comment]
@barius So far I have investigated:
* tqdm.notebook + ipywidgets: These packages are written in python, thus are hard to make use of directly in Typescript, I haven't fully checked how Jupyter Extension have managed to implement it, but I don't really want a python package to achieve a progress bar, I believe a native Typescript-ed one would suffice.
* Many open-source progress bars written in Typescript: They are heavily dependent on DOM, which [VSCode prohibits extensions to use](https://code.visualstudio.com/api/extension-capabilities/overview#restrictions). There are exceptions like [super-progress](https://github.com/s73obrien/super-progress/blob/master/src/super-progress.ts), but they are just not elegant enough. Just then I found:
* Native VSCode progressbar: Suprisingly the [cell-level progress bars](https://github.com/microsoft/vscode/blob/ec291c126878742ad640055ce604a58129cd088c/src/vs/workbench/contrib/notebook/browser/view/cellParts/cellProgressBar.ts#L14) have already been implemented, but VSCode team didn't expose them to extension developers, currently they only can be shown in an infinite fashion, the percentages of progress can't be manipulated by extensions even though [they support to](https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/ui/progressbar/progressbar.ts#L168).

I am going to post a issue, possibly a pull request to VSCode repo, trying to expose native VSCode progressbar api to extension developers. I believe this approach would be most efficient and elegant.
If VSCode team does not agree to, I will fall back to incorporating super-progress.

**Comment by barius** [comment]
![图片](https://github.com/allen-li1231/zeppelin-vscode/assets/2980072/ea515bdd-6e9f-4d0f-83ca-1a8b41cea0bb)
The progress bar is inpecable! Looks pretty good too! Really appreciate that!

I'm not familiar with vscode plugins. The progress bar updates on websocket events or SSE from Zeppelin side I guess?

Now with progress bar the plugin is (almost) functional-complete compare to Zeppelin's webUI 👍

**Comment by allen-li1231** [comment]
> ![图片](https://github.com/allen-li1231/zeppelin-vscode/assets/2980072/ea515bdd-6e9f-4d0f-83ca-1a8b41cea0bb)
> The progress bar is inpecable! Looks pretty good too! Really appreciate that!
> 
> I'm not familiar with vscode plugins. The progress bar updates on websocket events or SSE from Zeppelin side I guess?

The progressbar update is simpler than you think actually. Just implement Zeppelin's [paragraph API](https://zeppelin.apache.org/docs/0.10.1/usage/rest_api/notebook.html#get-a-paragraph-information) and update the parsed progress info to the progressbar module, voila!

Actually the whole functionaility of the extension is completely based on the Zeppelin REST API ;-P

Thank you for the advice, please do fire more issues if you have any left.

**Comment by allen-li1231** [comment]
[Track cell execution API PR progress](https://github.com/microsoft/vscode/pull/205204).
