### ISSUE TITLE
Can't seem to run the cell with magic `%spark.conf` and `%md`

### ISSUE THREAD

**Issue by flowy0** [allen-li1231/zeppelin-vscode#7]
Hi, 
It seems like the magic command `%spark.conf` is not recognised as cell that can be run. 
Any plans to support this?

Also found that the cell with `%md` is also ignored.

**Comment by allen-li1231** [comment]
Hi, is the spark.conf a legitimate kernel? Afaik it may refers to a method of spark instead of a kernel that runs code. If the same code works in the original web notebook, would you like to provide a screenshot on the code cell and the expected result?

**Comment by flowy0** [comment]
> Hi, I guess it is your cell language setting mismatches with the interpreter in magic command that causes the code not run as expected. I didn't mention in the readme but the magic command does not actually control how vscode identifies the language of the corresponding cell, you will have to also select the language in the bottom right corner of the cell to desired one: <img alt="Screenshot 2024-03-25 at 12 44 27 PM" width="1132" src="https://private-user-images.githubusercontent.com/34529879/316389523-72df9780-3bdf-48d9-9bca-7ed89c56abb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTEwNjUsIm5iZiI6MTcxMTM1MDc2NSwicGF0aCI6Ii8zNDUyOTg3OS8zMTYzODk1MjMtNzJkZjk3ODAtM2JkZi00OGQ5LTliY2EtN2VkODljNTZhYmI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3MTI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MmU3NWYzYjkwMDhhOWVlNGVkZDJkYjI0ZjUxOGVjMThkMzZlYTE1NmRjMTExZTIxYjQ2OWVlZTA3ZjA2OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.18g5yagmZ0OCUjKbffhGL-liJsfezqvJe9G7LZWpBj4"> Then try run again with your code.
> 
> If this is not the case that you have encountered, is the spark.conf a legitimate imterpreter? Afaik it may refer to a method of spark instead of a kernel that runs code. If you have set the correct language of the cell, didn't solve the problem, and the same code works in the original web notebook, would you like to provide a screenshot on the code cell and the expected output?

For `md`, i did login to the Zeppelin UI, the markdown cell is rendered correctly. 
Is this an expected output when i run a markdown cell?  
eg:
<img width="888" alt="image" src="https://github.com/allen-li1231/zeppelin-vscode/assets/9532712/6d1e0cbc-5167-453d-8fef-df2515ad26e5">

For `spark.conf`:

here is a sample of what i run in the regular zeppelin notebook, this sets some custom configs for the spark kernel. This does not have any output, however, i can set specific spark configs easily.

```
%spark.conf
spark.hadoop.fs.s3a.access.key {spark.ecs.user}
spark.hadoop.fs.s3a.secret.key {spark.ecs.password}
spark.kubernetes.executor.podNamePrefix g-plots-35p
zeppelin.k8s.interpreter.container.image my-python-interpreter-image
zeppelin.k8s.spark.container.image spark-interpreter image
```

**Comment by allen-li1231** [comment]
@flowy0 Let me know if you have more questions, otherwise this issue will be closed in 3 days.

**Comment by flowy0** [comment]
> For md, yes it is expected. One of the differences between Zeppelin UI and VSCode cell is that in VSCode, the magic command is treated as part of the markdown context when redering, while Zeppelin UI automatically hides the magic command when rendering.
> 
> For spark.conf, could you try setting the language mode of the cell to any language except for markdown? Despite the code being highlighted weird, can it be run anyway now? From my end: <img alt="Screenshot 2024-03-25 at 4 22 59 PM" width="1143" src="https://private-user-images.githubusercontent.com/34529879/316433083-e27db0ed-6c32-4c1d-845d-73e323d346ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0Mzc0NDIsIm5iZiI6MTcxMTQzNzE0MiwicGF0aCI6Ii8zNDUyOTg3OS8zMTY0MzMwODMtZTI3ZGIwZWQtNmMzMi00YzFkLTg0NWQtNzNlMzIzZDM0NmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA3MTIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNDM5N2I4NTk5OTMxYTQyMDlmMTYxYjEwYTQ0Mzk1YmIzMGJmMTg5OTY2MjFhZmUwZWJmNmQxZDljNjZhNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UDFnS2zUsTHzkxlnssFT1LEYWFmFqWcdsAF-FmChMXs"> FYI shortcut to run a cell: ctrl+enter.
> 
> The code seems like a shell script. I will add support to shell in the language mode in the next version.

After I changed it to run as Python, it seems to be fine and take effect. Thanks so much!
